from typing import Protocol

from app.dominio.entidades.usuario import Usuario


class ContratoRepositorioUsuario(Protocol):
    """Porta de persistência — domínio não conhece SQLAlchemy."""

    def buscar_por_auth_id(self, auth_id: str) -> Usuario | None: ...

    def buscar_por_id(self, usuario_id: int) -> Usuario | None: ...

    def buscar_por_ids(self, ids_usuarios: list[int]) -> list[Usuario]: ...

    def buscar_por_email(self, email: str) -> Usuario | None: ...

    def email_existe(self, email: str) -> bool: ...

    def criar(self, nome: str, email: str, password: str, **kwargs) -> Usuario: ...

    def atualizar(self, usuario: Usuario, dados: dict) -> Usuario: ...

    def autenticar(self, email: str, password: str) -> Usuario | None: ...
